all:
	pdflatex Alter.tex
	pdflatex Alter.tex
	mv Alter.pdf Alter-Award.pdf

clean:
	rm *.aux
	rm *.acn
	rm *.acr
	rm *.alg
	rm *.glg
	rm *.glo
	rm *.gls
	rm *.ist
	rm *.log
	rm *.out
	rm *.toc
	rm *.bbl
	rm *.blg
	rm *.dvi
	rm .* 
